/* 
  Sketch generated by the Arduino IoT Cloud Thing "iBeeShittdin"
  https://create.arduino.cc/cloud/things/109c2e65-17e3-43dd-affd-3b54fbcb04bc 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  CloudSwitch poopy;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include <Arduino.h>
#include "wiring_private.h"
#include "thingProperties.h"

const int lightPin = 2;

Uart mySerial (&sercom0, 5, 6, SERCOM_RX_PAD_1, UART_TX_PAD_0);

void SERCOM0_Handler()
{
  mySerial.IrqHandler();
}
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(lightPin, OUTPUT);
  
  pinPeripheral(5, PIO_SERCOM_ALT);
  pinPeripheral(6, PIO_SERCOM_ALT);
  mySerial.begin(9600);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  if (poopy) {
    Serial.println("poopy");
    digitalWrite(lightPin, HIGH);
    delay(500);
    onPoopyChange();
    poopy = false;
  }
  
}


void onPoopyChange() {
  // Do something
  mySerial.write(2);
  digitalWrite(lightPin, LOW);
}